# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ef29bf4012f849ed9a0d636457b0677b"
name = "bulkmatchphotos"
application_url = "https://bulk-photo-match.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders"

[auth]
redirect_urls = [
  "https://bulk-photo-match.fly.dev/auth/callback",
  "https://bulk-photo-match.fly.dev/auth/shopify/callback",
  "https://bulk-photo-match.fly.dev/api/auth/callback"
]
